# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Making of Year in Review
description: > # this means to ignore newlines until "baseurl:"
  For the last 5 years I have put together a personal year in review. What started as a fun way to share what I've been up to due to much of my professional work now being hidden behind closed doors has turned into a much more elaborate personal exploration of new web technologies and a collection of some interesting stats and a reflection of the year.
baseurl: "" # the subpath of your site, e.g. /blog
url: "making-of-year-in-review.rehanbutt.com" # the base hostname & protocol for your site

keywords: >
  year in review,making of,behind the scenes,bts,recap,devzgn,devzgner,personal review, personal recap,Design,UX,UI,webdev,branding,portfolio,site

# Build settings
markdown: kramdown
